database: postgres
spring:
  datasource:
    url: ${POSTGRES_URL:jdbc:postgresql://127.0.0.1:5432/resume}
    username: ${POSTGRES_USER:postgres}
    password: ${POSTGRES_PASS:12345}
    driver-class-name: org.postgresql.Driver
  sql:
    init:
      # SQL is written to be idempotent so this is safe
      mode: always
  jpa:
    show-sql: true
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create-drop
