server:
  servlet:
    context-path: /
  compression:
    enabled: true
    mime-types: text/html,text/xml,text/css,text/javascript,application/javascript,application/json
    min-response-size: 1024
  mvc:
    throw-exception-if-no-handler-found: true
