server:
  port: ${PORT:8080}
  servlet:
    context-path: /api

spring:
  profiles:
    active: "dev,spring-data-jpa"
  web:
    resources:
      add-mappings: false
  jpa:
    open-in-view: false

logging:
  level:
    org:
      springframework: INFO
