server:
  port: ${PORT:8080}
  servlet:
    context-path: /api

spring:
  profiles:
    active: h2,dev
  web:
    resources:
      add-mappings: false
  sql:
    init:
      schema-locations: classpath*:db/${database}/schema.sql
      data-locations: classpath*:db/${database}/data.sql
  jpa:
    open-in-view: false

database: h2

logging:
  level:
    org:
      springframework: INFO
