database:
  db-engine: h2

spring:
  datasource:
    url: jdbc:h2:mem:resume
    username: sa
    password:
    driver-class-name: org.h2.Driver
  sql:
    init:
      # SQL is written to be idempotent so this is safe
      mode: always
      schema-locations: classpath*:db/${database.db-engine}/schema.sql
      data-locations: classpath*:db/${database.db-engine}/data.sql
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    show-sql: true
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create-drop
