server:
  port: ${PORT:8080}
  servlet:
    context-path: /api

spring:
  profiles:
    active: dev
  web:
    resources:

      add-mappings: false
  sql:
    init:
      schema-locations: classpath*:db/${database.db-engine}/schema.sql
      data-locations: classpath*:db/${database.db-engine}/data.sql
  jpa:
    open-in-view: false

database:
  db-engine: h2

logging:
  level:
    org:
      springframework: INFO
