name: Java CI with Gradle

on:
  push:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project sources
        uses: actions/checkout@v3
      - name: Setup JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: Setup with Gradle
        uses: gradle/gradle-build-action@v2
        with:
          gradle-version: 8.1
      - name: Run tests with coverage with Gradle Wrapper
        run: ./gradlew :jacocoTestCoverageVerification :generateJacocoBadge